fix: error on comment-only YAML front matter
YAML front matters such as the following:

    ---
    # Nothing here.
    ---

previously resulted in:

    error: TypeError: Cannot set properties of null (setting 'content')

which as it turns out was caused by this Deno standard library peculiarity:

    > import {parse} from "https://deno.land/std@0.189.0/yaml/parse.ts";
    > parse('')
    undefined
    > parse('# test')
    null